name: 'Comment PR'

on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@latest
      - uses: actions/checkout@v1
      - name: Run Perfomance Test current Tag
        run: julia --project=test -e 'using Pkg; Pkg.instantiate()'
