name: 'Comment PR'

on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["master", nothing]
    steps:
      - uses: julia-actions/setup-julia@latest
      - uses: actions/checkout@v1
      - name: Run Perfomance Test
        env:
          test_version: ${{ matrix.version}}
        run: |
          julia --project=test -e 'using Pkg; Pkg.add(PackageSpec(name="PowerSimulationsDynamics", rev=ARGS[1])); Pkg.instantiate()' $test_version
          julia --project=test test/performance_test.jl $test_version
      - name: Read precompile results
        id: precompile_results
        run: |
          body="$(cat precompile_time.txt)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "::set-output name=body::$body"
      - name: Read execute results
        id: execute_results
        run: |
          body="$(cat execute_time.txt)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "::set-output name=body::$body"
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Performance Results
      - name: Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Performance Results
            | Version      | Precompile Time |
            | :---        |    :----:   |
            ${{ steps.precompile_results.outputs.body }}

            | Version      | Execute Time |
            | :---        |    :----:   |
            ${{ steps.execute_results.outputs.body }}
      - name: Update comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            Performance Results
            | Version      | Precompile Time |
            | :---        |    :----:   |
            ${{ steps.precompile_results.outputs.body }}

            | Version      | Execute Time |
            | :---        |    :----:   |
            ${{ steps.execute_results.outputs.body }}
          edit-mode: replace
